export const AI_CONNECT_TIMEOUT_MS = 30_000
export const AI_STREAM_READ_TIMEOUT_MS = 60_000

export const MAX_TOKENS_ACTION = 4096
export const MAX_TOKENS_FRAGMENT = 2000
export const MAX_TOKENS_SUGGEST = 4000

export const CONTEXT_TRUNCATE_FULL = 6000
export const CONTEXT_TRUNCATE_REGEN = 4000
export const CONTEXT_TRUNCATE_CHAPTER = 3000
export const CONTEXT_TRUNCATE_INLINE = 2000
export const CONTEXT_TRUNCATE_FRAGMENT = 1000
export const CONTEXT_TRUNCATE_WORLD = 500

export const MAX_TOKENS_REVIEW = 4096
export const REVIEW_MAX_CHAPTERS = 10
